Receive station_id from Core and push to module as an env var
filecoin-station/zinnia pull request #520
Opened 2024-04-12 21:34 UTC by PatrickNercessian

DRAFT: DO NOT MERGE

2024-04-15 07:08 UTC, juliangruber commented on .gitignore
> +*.DS_Store
```suggestion
*.DS_Store

```

2024-04-15 07:08 UTC, juliangruber commented on daemon/main.rs
> +            station_id: "zinnia-dev".to_string(),
I think that only passing through the environment variable "station_id" isn't ideal, as Zinnia ideally doesn't know anything about Station. Instead there should be a way to pass any key value pair into the module context. I believe that implementing this is out of scope for this PR, so just noting here that I would like to improve this in the future.

2024-04-15 11:42 UTC, bajtos requested changes
Nice! The changes look great. 👏🏻 

I'd like to change one minor detail; the rest LGTM. 👍🏻 

Also let's wait for the CI results to ensure all is green.

2024-04-15 11:42 UTC, bajtos commented on daemon/args.rs
> +    #[arg(long, short = 's', env = "STATION_ID", name = "STATION ID")]
I feel the short-hand name `-s` is confusing, e.g. `--state_root` can be abbreviated as `-s` too.

Let's not define any short-hand name for this arg.

```suggestion
    #[arg(long, env = "STATION_ID", name = "STATION ID")]
```

2024-04-17 07:29 UTC, bajtos commented
https://github.com/filecoin-station/zinnia/actions/runs/8692944647/job/23914200368?pr=520

```
Error: Unknown release type "Feat" found in pull request title "Feat: Receive station_id from Core and push to module as an env var". 

Available types:
 - feat
 - fix
 - chore
 - docs
 - deps
 - test
 - ci
 - refactor
```

To speed up the process, I changed the PR from "draft" to a regular one, update the PR title and will proceed to land & publish this change.

2024-04-17 07:30 UTC, bajtos approved these changes

2024-04-17 07:38 UTC, merged